# Generated by Django 5.0.4 on 2024-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passanger',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passangers', to='flights.flight'),
        ),
    ]
